/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <vector>
#include <string>

#include "main.h"

void SystemClock_Config(void);
void MX_FREERTOS_Init(void);


int main(void)
{
	std::vector<int> v(1, 0);
	std::vector<int> v2(10, 50);
	std::vector<int> v3(1000, 10);
    std::string str = "123";
    std::string str2 = "123133";


    HAL_Init();

	/* Loop forever */
	for(;;);
}
